AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - db/**/*.rb

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - test/**/*.rb
    - config/**/*.rb

Metrics/LineLength:
  Exclude:
    - test/**/*.rb
    - config/**/*.rb

Metrics/PerceivedComplexity:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

# these are not particularly helpful
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
# Metrics/ParameterLists:
#   Enabled: false
# Metrics/CyclomaticComplexity:
#   Enabled: false
